apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketflow.fullname" . }}
  labels:
    {{- include "ticketflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "ticketflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
